-
  name: 'Frontpage'
  uriPattern: ''
  defaults:
    '@package':    'Newsfix.Core'
    '@controller': 'Frontpage'
    '@action': 'index'
    '@format': 'html'


-
  name: 'Flow'
  uriPattern: '<FlowSubroutes>'
  defaults:
    '@format': 'html'
  subRoutes:
    FlowSubroutes:
      package: TYPO3.Flow
